package validationrules.core;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType;
import function uk.gov.hmcts.reform.roleassignment.domain.service.common.ValidationModelService.logMsg;

rule "prm_create_org_role"
when
    $rq: Request(clientId == "am_org_role_mapping_service")
    $ra: RoleAssignment(
             status == Status.CREATE_REQUESTED,
             roleType == RoleType.ORGANISATION,
             roleCategory == RoleCategory.PROFESSIONAL)
then
    $ra.setStatus(Status.CREATE_APPROVED);
    $ra.log("Create approved : prm_create_org_role");
    update($ra);
    logMsg("Rule : prm_create_org_role");
end;

rule "prm_delete_org_role"
when
    $rq: Request(clientId == "am_org_role_mapping_service")
    $ra: RoleAssignment(
             status == Status.DELETE_REQUESTED,
             roleType == RoleType.ORGANISATION,
             roleCategory == RoleCategory.PROFESSIONAL)
then
    $ra.setStatus(Status.DELETE_APPROVED);
    $ra.log("Delete approved : prm_delete_org_role");
    update($ra);
    logMsg("Rule : prm_delete_org_role");
end;
