package validationrules.probate;
import uk.gov.hmcts.reform.roleassignment.domain.model.Assignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Classification;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.roleassignment.domain.model.ExistingRoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.CaseAllocatorApproval;
import uk.gov.hmcts.reform.roleassignment.domain.model.Case;
import function uk.gov.hmcts.reform.roleassignment.domain.service.common.ValidationModelService.logMsg;
import uk.gov.hmcts.reform.roleassignment.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.FeatureFlagEnum;
import uk.gov.hmcts.reform.roleassignment.util.ValidationUtil;

import java.time.ZonedDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;

/*
 * The "allocated-ctsc-caseworker" case role
 */
rule "probate_allocated_ctsc_caseworker_create_case_roles_v1"
when
    $f : FeatureFlag(status && flagName == FeatureFlagEnum.PROBATE_WA_1_0.getValue())
    $ca: CaseAllocatorApproval(
                 roleAssignment.status == Status.CREATE_REQUESTED,
                 roleAssignment.attributes["jurisdiction"].asText() == "PROBATE",
                 roleAssignment.attributes["caseType"].asText() == "GrantOfRepresentation",
                 roleAssignment.classification == Classification.RESTRICTED,
                 roleAssignment.grantType == GrantType.SPECIFIC,
                 roleAssignment.roleName == "allocated-ctsc-caseworker")
         ExistingRoleAssignment(
                 actorId == $ca.getRoleAssignment().actorId,
                 roleType == RoleType.ORGANISATION,
                 roleName in ("ctsc", "ctsc-team-leader"),
                 attributes["jurisdiction"] != null && attributes["jurisdiction"].asText() == "PROBATE")
then
    $ca.getRoleAssignment().setStatus(Status.CREATE_APPROVED);
    $ca.getRoleAssignment().log("Stage 1 approved : probate_allocated_ctsc_caseworker_create_case_roles_v1");
    update($ca.getRoleAssignment());
    logMsg("Rule : probate_allocated_ctsc_caseworker_create_case_roles_v1");
end;

/*
 * The "allocated-tribunal-caseworker" case role
 */
rule "probate_allocated_tribunal_caseworker_create_case_roles_v1"
when
    $f : FeatureFlag(status && flagName == FeatureFlagEnum.PROBATE_WA_1_0.getValue())
    $ca: CaseAllocatorApproval(
                 roleAssignment.status == Status.CREATE_REQUESTED,
                 roleAssignment.attributes["jurisdiction"].asText() == "PROBATE",
                 roleAssignment.roleName == "allocated-tribunal-caseworker")
         ExistingRoleAssignment(
                 actorId == $ca.getRoleAssignment().actorId,
                 roleType == RoleType.ORGANISATION,
                 roleName in ("tribunal-caseworker", "senior-tribunal-caseworker"),
                 attributes["jurisdiction"] != null && attributes["jurisdiction"].asText() == "PROBATE")
then
    $ca.getRoleAssignment().setStatus(Status.CREATE_APPROVED);
    $ca.getRoleAssignment().log("Stage 1 approved : probate_allocated_tribunal_caseworker_create_case_roles_v1");
    update($ca.getRoleAssignment());
    logMsg("Rule : probate_allocated_tribunal_caseworker_create_case_roles_v1");
end;

/*
 * The "allocated-tribunal-caseworker" case role
 */
rule "probate_allocated_legal_adviser_create_case_roles_v1"
when
    $f : FeatureFlag(status && flagName == FeatureFlagEnum.PROBATE_WA_1_0.getValue())
    $ca: CaseAllocatorApproval(
                 roleAssignment.status == Status.CREATE_REQUESTED,
                 roleAssignment.attributes["jurisdiction"].asText() == "PROBATE",
                 roleAssignment.attributes["caseType"].asText() == "GrantOfRepresentation",
                 roleAssignment.classification == Classification.RESTRICTED,
                 roleAssignment.grantType == GrantType.SPECIFIC,
                 roleAssignment.roleName == "allocated-tribunal-caseworker")
         ExistingRoleAssignment(
                 actorId == $ca.getRoleAssignment().actorId,
                 roleType == RoleType.ORGANISATION,
                 roleName == "senior-tribunal-caseworker",
                 attributes["jurisdiction"] != null && attributes["jurisdiction"].asText() == "PROBATE")
then
    $ca.getRoleAssignment().setStatus(Status.CREATE_APPROVED);
    $ca.getRoleAssignment().log("Stage 1 approved : probate_allocated_legal_adviser_create_case_roles_v1");
    update($ca.getRoleAssignment());
    logMsg("Rule : probate_allocated_legal_adviser_create_case_roles_v1");
end;