package validationrules.core;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType;
import function uk.gov.hmcts.reform.roleassignment.domain.service.common.ValidationModelService.logMsg;
/*
 * mapping for judicial case flow

 */
rule "judicial_case_role_mapping_service_create"
when
    $rq: Request(
                 assignerId == authenticatedUserId)
    $ra: RoleAssignment(status == Status.CREATE_REQUESTED,
                          roleType == RoleType.CASE,
                          roleCategory == RoleCategory.JUDICIAL)
then
    $ra.setStatus(Status.CREATE_APPROVED);
    $ra.log("Create approved : judicial_case_role_mapping_service_create");
    update($ra);
    logMsg("Rule : judicial_case_role_mapping_service_create");
end;


rule "judicial_case_role_mapping_service_delete"
when
    $rq: Request(assignerId == authenticatedUserId)

    $ra: RoleAssignment(
             status == Status.DELETE_REQUESTED,
             roleType == RoleType.CASE,
             roleCategory == RoleCategory.JUDICIAL)
then
    $ra.setStatus(Status.DELETE_APPROVED);
    $ra.log("Delete approved : judicial_case_role_mapping_service_delete");
    update($ra);
    logMsg("Rule :: judicial_case_role_mapping_service_delete");
end;
