spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.restclient.autoconfigure.RestClientAutoConfiguration
  cloud:
    compatibility-verifier:
      enabled: false
    discovery:
      enabled: false
