package validationrules



import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.ExistingRoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;


rule "R05_validate_existing_requester_details" salience 70
	when
	   $roleAssignment: RoleAssignment()
	                    RoleAssignment(roleType == RoleType.CASE,$roleAssignment.getStatus() == Status.ROLE_VALIDATED_BY_PATTERN)
	   $request: Request()
	   ExistingRoleAssignment(actorId == $request.getAssignerId())

	then
	  System.out.println("R05_validate_existing_requester_details::: ");
	 	$request.setStatus(Status.REQUEST_VALIDATED);
		$request.setLog(String.format("Existing Requester & Assignee details has been validated by the rule : %s ","R05_validate_existing_requester_details"));

end

rule "R06_validate_existing_assignee_details" salience 65
	when
	   $roleAssignment: RoleAssignment()
	                    RoleAssignment(roleType == RoleType.CASE,$roleAssignment.getStatus() == Status.ROLE_VALIDATED_BY_PATTERN)

	   $request: Request()
	             Request($request.getStatus() == Status.REQUEST_VALIDATED)

    ExistingRoleAssignment(actorId == $roleAssignment.getActorId())

	then
	  System.out.println("Rule Name : R06_validate_existing_assignee_details::: ");
	  $roleAssignment.setStatus(Status.ROLE_VALIDATED);
	 	$request.setLog(String.format("Existing Requester & Assignee details has been validated by the rule : %s ","R06_validate_existing_assignee_details"));

end

rule "R07_validate_existing_details_fails" salience 60
	when
	   $roleAssignment: RoleAssignment()
	                    RoleAssignment(roleType == RoleType.CASE, $roleAssignment.getStatus() != Status.ROLE_VALIDATED)
	   $request: Request()
	            Request($request.getStatus() != Status.REQUEST_VALIDATED)
	           not ExistingRoleAssignment()

	then
	   System.out.println("Rule Name : R07_validate_existing_details_fails::: ");
	 	$request.setStatus(Status.REJECTED);
	 	$roleAssignment.setStatus(Status.REJECTED);
		$request.setLog(String.format("Existing Requester & Assignee details has been failed by the rule : %s ","R07_validate_existing_details_fails"));

end
