package validationrules

global uk.gov.hmcts.reform.roleassignment.domain.service.common.RetrieveDataService retrieveDataService

import uk.gov.hmcts.reform.roleassignment.domain.model.Case;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Classification;

rule "R09_retrieve_case_detail" salience 55
	when
	   $request: Request(status == Status.REQUEST_VALIDATED)
	   $roleAssignment: RoleAssignment()
	                   RoleAssignment(roleType == RoleType.CASE,$roleAssignment.getStatus() == Status.ROLE_VALIDATED,roleName == "tribunal-caseworker")
	                   RoleAssignment(attributes["caseId"]!=null, $caseId : attributes["caseId"])

	   not Case (id == $caseId.asText() )

	then
	  	System.out.println("R09_retrieve_case_details::");
	 	insert (retrieveDataService.getCaseById($caseId.asText()));
		$request.setLog(String.format("Case has been inserted by the rule : %s ","R09_retrieve_case_details"));

end

rule "R10_case_validation" salience 50
	when
	  $request: Request(status == Status.REQUEST_VALIDATED)
	  $roleAssignment:RoleAssignment()
	                  RoleAssignment(roleName == "tribunal-caseworker",$roleAssignment.getStatus() == Status.ROLE_VALIDATED,roleType == RoleType.CASE,getGrantType == GrantType.SPECIFIC, classification == Classification.PUBLIC)
	   Case(caseTypeId == "ASYLUM",jurisdiction == "IA")


	then
	System.out.println("R10_case_validation::");
	 	$roleAssignment.setStatus(Status.APPROVED);

		$roleAssignment.setLog(String.format("Requested role has been approved by the rule : %s ","R10_case_validation"));
		$request.setLog(String.format("Request has been approved by the rule : %s ","R10_case_validation"));

end


//Rues for without tribunal-caseworker role for case
rule "R233_non_tc_role_validation" salience 48
	when
	  $request: Request(status == Status.REQUEST_VALIDATED)
	  $roleAssignment:RoleAssignment()
	                RoleAssignment(roleName != "tribunal-caseworker",$roleAssignment.getStatus() == Status.ROLE_VALIDATED,roleType == RoleType.CASE)
	then
	System.out.println("R233_non_tc_role_validation::");
	 	$roleAssignment.setStatus(Status.APPROVED);

		$roleAssignment.setLog(String.format("Requested role has been approved by the rule : %s ","R233_non_tc_role_validation"));
		$request.setLog(String.format("Request has been approved by the rule : %s ","R233_non_tc_role_validation"));

end

rule "R11_case_validation_fail" salience 45
when
    $roleAssignment: RoleAssignment()
     RoleAssignment($roleAssignment.getStatus()!=Status.APPROVED,roleType == RoleType.CASE)

then
System.out.println("R11_case_validation_fail::");
$roleAssignment.setLog(String.format("Requested role has not been approved by the rule R11_case_validation_fail "));
$roleAssignment.setStatus(Status.REJECTED);
end;
