package validationrules

global uk.gov.hmcts.reform.roleassignment.domain.service.common.RetrieveDataService retrieveDataService

import uk.gov.hmcts.reform.roleassignment.domain.model.Case;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;

rule "R01_retrieve_case_detail" salience 100
	when
	  $request : Request()
	  $role : RoleAssignment(attributes["caseId"]!=null, $caseId : attributes["caseId"])
	   not Case (id == $caseId.asText() )

	then
   	insert (retrieveDataService.getCaseById($caseId.asText()));
		$request.setLog(String.format("Case has been inserted by the rule : %s ","R01_retrieve_case_detail"));

end
