 package validationrules
 import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
 import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
 import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;



rule "R06_validate_details_fails" salience 75
when
       $request:        Request()
  	   $roleAssignment: RoleAssignment(status != Status.APPROVED)
then
  	System.out.println("R06_validate_details_fails::");
  	$roleAssignment.setStatus(Status.REJECTED);
  	$roleAssignment.setLog(String.format("Requested role has been rejected by the rule : %s ","R06_validate_details_fails"));
    $request.setLog(String.format("Request has been rejected by the rule : %s ","R06_validate_details_fails"));

end
