 package validationrules
 import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
 import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
 import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
 import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;



rule "R06_validate_details_fails" salience 75
when
       $request:        Request(requestType == RequestType.CREATE)
  	   $roleAssignment: RoleAssignment(status != Status.APPROVED)
then
  	System.out.println("R06_validate_details_fails::");
  	$roleAssignment.setStatus(Status.REJECTED);
  	$roleAssignment.setLog(String.format("Requested role has been rejected by the rule : %s ","R06_validate_details_fails"));
    $request.setLog(String.format("Request has been rejected by the rule : %s ","R06_validate_details_fails"));

end

rule "R13_delete_validation_fail" salience 60
when
    $request  : Request(id!= null,requestType == RequestType.DELETE)
    $roleAssignment  : RoleAssignment(status!= Status.APPROVED)

then
    $request.setLog(String.format("Request has been rejected by rule :R13_delete_validation_fail "));
    $roleAssignment.setLog(String.format("Requested role has been rejected by the rule : %s ","R13_delete_validation_fail"));
    $roleAssignment.setStatus(Status.REJECTED);
end;
