package validationrules
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.roleassignment.domain.model.RequestedRole;
rule "request validation for creation" salience 90

when
$request  : Request(id!= null,requestType == RequestType.CREATE,status == Status.CREATED)
            Request( created !=null,process in (GrantType.SPECIFIC.toString(),GrantType.STANDARD.toString(),GrantType.CHALLENGED.toString()))
            Request(replaceExisting == Boolean.TRUE, process !=null, reference != null) or Request(replaceExisting == Boolean.FALSE)

then
$request.setLog(String.format("request has been validated by the rule  %s with correlation Id %s","request validation for creation",$request.getCorrelationId()));
$request.setStatus(Status.VALIDATED);
end;


//**** rules for delete ****
rule "request validation for delete" salience 80

when
$request  : Request(id!= null,requestType == RequestType.DELETE,status == Status.CREATED)
$requestedRole  : RequestedRole(id!= null)
then
$request.setLog(String.format("request has been validated by the  %s rule with correlation Id %s","request validation for delete",$request.getCorrelationId()));
$request.setLog(String.format("Requested Role has been deleted by the  %s rule with correlation Id %s","request validation for delete",$request.getCorrelationId()));
$requestedRole.setStatus(Status.APPROVED);
end;






//******* create role reuest validation rule *****
// clientId(service id from s2s token ) must be am_role_assignment_service
// requesttype must be create
// status must be create
//process == SPECIFIC
// if replaceExisting is true then process & reference must not be null
//if requestType == create, then roleassignmentId should be null/empty.rule
//if requestType == delete and delete endpoint is based on assignment id, then roleassignmentId must not be null.
// created and lastupdatedtime should be not null.
// request Id should not be null.




