package validationrules
import uk.gov.hmcts.reform.assignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.assignment.domain.model.Request;
import uk.gov.hmcts.reform.assignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.assignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.assignment.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.assignment.domain.model.enums.RoleType
import uk.gov.hmcts.reform.assignment.domain.model.Role;


rule "R05_assignment_validation" salience 75

when
$roleAssignment  : RoleAssignment()
$request        : Request()
                  Request($request.getStatus() == Status.REQUEST_VALIDATED)
                  Request(requestType == RequestType.CREATE)
                  Request(clientId != "xui") or (Request(clientId == "xui") and RoleAssignment(roleType==RoleType.CASE))
                  Request(clientId != "organization_mapping") or (Request(clientId == "organization_mapping") and RoleAssignment(roleType==RoleType.ORGANISATION))
                  RoleAssignment(id!=null, status==Status.CREATED) or RoleAssignment(status==Status.LIVE)

then
$roleAssignment.setLog(String.format("Requested Role has been validated by rule : R05_assignment_validation "));
$roleAssignment.setStatus(Status.ROLE_VALIDATED);
end;


rule "R06_assignment_validation_fail" salience 70
when
$roleAssignment  : RoleAssignment()
                   Request(requestType == RequestType.CREATE)
                   RoleAssignment($roleAssignment.getStatus()!=Status.ROLE_VALIDATED)

then
$roleAssignment.setLog(String.format("Requested Role  validation fail by rule : %s","R05_assignment_validation"));
$roleAssignment.setStatus(Status.ROLE_NOT_VALIDATED);
end;




