package validationrules
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;

rule "R02_request_validation" salience 90
when
$request  : Request(id!= null,created !=null,status == Status.CREATED)
            Request(requestType == RequestType.CREATE)

then
$request.setLog(String.format("Request has been validated by rule : %s","R02_request_validation"));
$request.setStatus(Status.REQUEST_VALIDATED);
end;

//**** rules for delete ****
rule "R03_delete_validation" salience 85

when
$request  : Request(id!= null,requestType == RequestType.DELETE,status == Status.CREATED)
roleAssignment  : RoleAssignment(id!= null)
then
$request.setLog(String.format("Requested has been approved by rule :R03_delete_validation "));
$request.setStatus(Status.REQUEST_VALIDATED);
roleAssignment.setStatus(Status.APPROVED);
end;

rule "R03X_delete_validation_fail" salience 83

when
$request  : Request(id!= null,requestType == RequestType.DELETE,status == Status.CREATED)
$roleAssignment  : RoleAssignment()
                   RoleAssignment($roleAssignment.getStatus()!= Status.APPROVED)

then
$request.setLog(String.format("Request has been rejected by rule :R03X_delete_validation_fail "));
$roleAssignment.setStatus(Status.REJECTED);
end;


rule "R04_request_validation_fail" salience 80
when
$request  : Request()
            Request($request.getStatus()!=Status.REQUEST_VALIDATED)

then
$request.setLog(String.format("Request  validation fail by rule : %s","R02_request_validation"));
$request.setStatus(Status.REQUEST_NOT_VALIDATED);
end;






