package validationrules.dev;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType;

/*
 *
 */
rule "development_superuser"
when
    $rq: Request(
             requestType == RequestType.CREATE,
             process == "DEVELOPMENT_SUPERUSER")
    $ra: RoleAssignment(
             status == Status.CREATED)
then
    $ra.setStatus(Status.STAGE_1_APPROVED);
    $ra.log("Stage 1 approved : staff_organisational_role_mapping_service_create");
    update($ra);
    System.out.println("Rule :development_superuser");
end;

rule "development_superuser_warning"
when
    $rq: Request()
then
    System.err.println("*************************************************************************************************");
    System.err.println("*************************************************************************************************");
    System.err.println("*************************************************************************************************");
    System.err.println("*************************************************************************************************");
    System.err.println("*************************************************************************************************");
    System.err.println("*************************************************************************************************");
    System.err.println("******* DEVELOPMENT SUPERUSER MODE IS AVAILABLE.  THIS MUST NOT RUN IN PRODUCTION. **************");
    System.err.println("*************************************************************************************************");
    System.err.println("*************************************************************************************************");
    System.err.println("*************************************************************************************************");
    System.err.println("*************************************************************************************************");
    System.err.println("*************************************************************************************************");
    System.err.println("*************************************************************************************************");
    System.err.println("*************************************************************************************************");
end;
