package validationrules.fr;
import uk.gov.hmcts.reform.roleassignment.domain.model.Assignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Classification;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.roleassignment.domain.model.ExistingRoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.CaseAllocatorApproval;
import uk.gov.hmcts.reform.roleassignment.domain.model.Case;
import function uk.gov.hmcts.reform.roleassignment.domain.service.common.ValidationModelService.logMsg;
import uk.gov.hmcts.reform.roleassignment.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.FeatureFlagEnum;
import uk.gov.hmcts.reform.roleassignment.util.ValidationUtil;

import java.time.ZonedDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;

/*
 * The "allocated-judge" case role
 */
rule "fr_allocated_judge_create_case_roles_v1"
when
    $f : FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $ca: CaseAllocatorApproval(
                 roleAssignment.status == Status.CREATE_REQUESTED,
                 roleAssignment.attributes["jurisdiction"].asText() == "DIVORCE",
                 roleAssignment.attributes["caseType"].asText() == "FinancialRemedyMVP2",
                 roleAssignment.classification == Classification.RESTRICTED,
                 roleAssignment.grantType == GrantType.SPECIFIC,
                 roleAssignment.roleName == "allocated-judge")
         ExistingRoleAssignment(
                 actorId == $ca.getRoleAssignment().actorId,
                 roleType == RoleType.ORGANISATION,
                 roleName in ("judge", "fee-paid-judge"),
                 attributes["jurisdiction"] != null && attributes["jurisdiction"].asText() == "DIVORCE",
                 attributes["caseType"] != null && attributes["caseType"].asText() == "FinancialRemedyMVP2")
then
    $ca.getRoleAssignment().setStatus(Status.CREATE_APPROVED);
    $ca.getRoleAssignment().log("Stage 1 approved : fr_allocated_judge_create_case_roles_v1");
    update($ca.getRoleAssignment());
    logMsg("Rule : fr_allocated_judge_create_case_roles_v1");
end;

/*
 * The "hearing-judge" case role
 */
rule "fr_hearing_judge_create_case_roles_v1"
when
    $f : FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $ca: CaseAllocatorApproval(
                 roleAssignment.status == Status.CREATE_REQUESTED,
                 roleAssignment.attributes["jurisdiction"].asText() == "DIVORCE",
                 roleAssignment.attributes["caseType"].asText() == "FinancialRemedyMVP2",
                 roleAssignment.classification == Classification.RESTRICTED,
                 roleAssignment.grantType == GrantType.SPECIFIC,
                 roleAssignment.roleName == "hearing-judge")
         ExistingRoleAssignment(
                 actorId == $ca.getRoleAssignment().actorId,
                 roleType == RoleType.ORGANISATION,
                 roleName in ("judge", "fee-paid-judge"),
                 attributes["jurisdiction"] != null && attributes["jurisdiction"].asText() == "DIVORCE",
                 attributes["caseType"] != null && attributes["caseType"].asText() == "FinancialRemedyMVP2")
then
    $ca.getRoleAssignment().setStatus(Status.CREATE_APPROVED);
    $ca.getRoleAssignment().log("Stage 1 approved : fr_hearing_judge_create_case_roles_v1");
    update($ca.getRoleAssignment());
    logMsg("Rule : fr_hearing_judge_create_case_roles_v1");
end;

/*
 * The "lead-judge" case role
 */
rule "fr_lead_judge_create_case_roles_v1"
when
    $f : FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $ca: CaseAllocatorApproval(
                 roleAssignment.status == Status.CREATE_REQUESTED,
                 roleAssignment.attributes["jurisdiction"].asText() == "DIVORCE",
                 roleAssignment.attributes["caseType"].asText() == "FinancialRemedyMVP2",
                 roleAssignment.classification == Classification.RESTRICTED,
                 roleAssignment.grantType == GrantType.SPECIFIC,
                 roleAssignment.roleName == "lead-judge")
         ExistingRoleAssignment(
                 actorId == $ca.getRoleAssignment().actorId,
                 roleType == RoleType.ORGANISATION,
                 roleName in ("judge"),
                 attributes["jurisdiction"] != null && attributes["jurisdiction"].asText() == "DIVORCE",
                 attributes["caseType"] != null && attributes["caseType"].asText() == "FinancialRemedyMVP2")
then
    $ca.getRoleAssignment().setStatus(Status.CREATE_APPROVED);
    $ca.getRoleAssignment().log("Stage 1 approved : fr_lead_judge_create_case_roles_v1");
    update($ca.getRoleAssignment());
    logMsg("Rule : fr_lead_judge_create_case_roles_v1");
end;
