package roleassignmentvalidation

global uk.gov.hmcts.reform.roleassignment.domain.service.common.createroles.CreateRoleAssignmentOrchestrator services

import uk.gov.hmcts.reform.roleassignment.model.*

rule "load cases for case roles" salience 100
	when
		$role : RequestedRole ( $caseId : attributes["caseId"] )
		not Case ( id == $caseId )
	then
		insert ( services.caseService.getCaseById($caseId) );

end
