package roleassignmentvalidation
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;

rule "request validation"

when
$request  : Request(id!= null,requestType == RequestType.CREATE,status == Status.CREATED,replaceExisting == Boolean.TRUE, process == "SPECIFIC",
            created !=null,lastUpdateTime !=null)

then
$request.setStatus(Status.APPROVED);

end;




//******* create role reuest validation rule *****
// clientId(service id from s2s token ) must be am_role_assignment_service
// requesttype must be create
// status must be create
//process == SPECIFIC
// if replaceExisting is true then process & reference must not be null
//if requestType == create, then roleassifgnmentId should be null/empty.rule
//if requestType == delete and delete endpoint is based on assignment id, then roleassifgnmentId must not be null.
// created and lastupdatedtime should be not null.
// request Id should not be null.

// ********* Role Assignment validation ***** create role assignmenment validation rule

// role assignment Id should not be null.
// if clint id in request == xui then role type in assignment must be == CASE
// if client id in request == organization_mapping service then role type in assignment must be == ORGANIZATION
// roleName should belong to  existing  Role model object
// The Requester.Classification shold be >= roleassignment.clasiffication
// request.process dhould be == roleassgnment.grantType
// status must be create
// beginTime >= currentTime , endTime >= currentTime & endTime > beginTime
