#!/usr/bin/env bash

set -e

echo "Strting init.db.sh.........."

echo $ROLE_ASSIGNMENT_DB_USERNAME
echo $ROLE_ASSIGNMENT_DB_PASSWORD


# Create role and database
psql -v ON_ERROR_STOP=1 --username postgres --set USERNAME=$ROLE_ASSIGNMENT_DB_USERNAME --set PASSWORD=$ROLE_ASSIGNMENT_DB_PASSWORD <<-EOSQL
  CREATE USER :USERNAME WITH PASSWORD ':PASSWORD';
  CREATE DATABASE role_assignment
    WITH OWNER = :USERNAME
    ENCODING = 'UTF-8'
    CONNECTION LIMIT = -1;
  ALTER SCHEMA public OWNER TO :USERNAME;

EOSQL
