package uk.gov.hmcts.reform.roleassignment.domain.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.JsonNode;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Classification;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.util.JacksonUtils;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@SuperBuilder
@NoArgsConstructor
@Data
@AllArgsConstructor
public abstract class Assignment {
    private UUID id; //this will be generated by application while saving request entity.
    private ActorIdType actorIdType;
    private String actorId;
    private RoleType roleType;
    private String roleName;
    private Classification classification;
    private GrantType grantType;
    private RoleCategory roleCategory;
    private boolean readOnly;
    private ZonedDateTime beginTime;
    private ZonedDateTime endTime;


    private String process; //need to map from request
    private String reference; //need to map from request
    private Integer statusSequence; //this will be populated from status entity. Need to extend status entity.
    private Status status; //this will be set by app default = created
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private ZonedDateTime created;
    private String log; //this will be set app based on drool validation rule name on individual assignments.
    private Map<String, JsonNode> attributes;
    private JsonNode notes;
    private List<String> authorisations;

    public void log(String message) {
        log = (log == null ? "" : log + "\n") + message;
    }

    public void setAttribute(String key, String value) {
        JsonNode valueNode = JacksonUtils.convertValueJsonNode(value);
        attributes.put(key, valueNode);
    }
}
