package uk.gov.hmcts.reform.roleassignment.domain.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;

import java.time.LocalDateTime;
import java.util.UUID;

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Request {

    public UUID id; //this will be generated by application while saving request entity.
    public String clientId; // this will be retrieved by app using s2s token
    public UUID authenticatedUserId; // this will be retrieved by app from user-token.
    public String correlationId;//If it is empty then need to be generated by app.
    public UUID assignerId;
    public RequestType requestType;
    public String process;
    public String reference;
    public boolean replaceExisting;
    public UUID roleAssignmentId;
    public Status status; //this will be set by app default = created
    public LocalDateTime created; //this will be set by app
    public String log; //this will be set app based on drool validation rule name on individual assignments.

}
