package uk.gov.hmcts.reform.roleassignment.domain.model;

import com.fasterxml.jackson.databind.JsonNode;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Classification;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.UUID;


@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
public class RoleAssignment {

    public UUID id; //this will be generated by application while saving request entity.
    public ActorIdType actorIdType;
    public UUID actorId;
    public RoleType roleType;
    public String roleName;
    public Classification classification;
    public GrantType grantType;
    public RoleCategory roleCategory;
    public boolean readOnly;
    public LocalDateTime beginTime;
    public LocalDateTime endTime;


    public String process; //need to map from request
    public String reference; //need to map from request
    public Integer statusSequence; //this will be populated from status entity. Need to extend status entity.
    public Status status; //this will be set by app default = created
    public LocalDateTime created; //this will be set by app
    public String log; //this will be set app based on drool validation rule name on individual assignments.
    public Request request;
    public Map<String, JsonNode> attributes;
    public JsonNode notes;
}
