package validationrules.core
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;

/*
 * 
 */
rule "create_request_initial_role_assignment_status"
when
         Request(
             requestType == RequestType.CREATE)
    $ra: RoleAssignment(
             status == Status.CREATED)
then
	$ra.setStatus(Status.CREATE_REQUESTED)
	System.out.println("Rule : delete_request_initial_role_assignment_status");
end;

/*
 * 
 */
rule "create_request_replace_existing_initial_role_assignment_status"
when
         Request(
             requestType == RequestType.CREATE,
             replaceExisting == true)
    $ra: RoleAssignment(
             status == Status.LIVE)
then
	$ra.setStatus(Status.DELETE_REQUESTED)
	System.out.println("Rule : create_request_replace_existing_initial_role_assignment_status");
end;


/*
 * 
 */
rule "delete_request_initial_role_assignment_status"
when
         Request(
             requestType == RequestType.DELETE)
    $ra: RoleAssignment()
then
	$ra.setStatus(Status.DELETE_REQUESTED)
	System.out.println("Rule : delete_request_initial_role_assignment_status");
end;