package validationrules.core;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType;

/*
 * Generic rule for validation of roles created by the staff organisational
 * role mapping service.  The mapping service can create any organisational
 * staff roles, and is trusted to get the role attributes right, but note
 * that validation against standard role patterns will still be applied in
 * a later stage of validation.
 */
rule "judicial_case_role_mapping_service_create"
when
    $rq: Request(
             requestType == RequestType.CREATE )

    $ra: RoleAssignment(
            //Need to check Status Live when replaceExiting=true
             status in (Status.CREATED,Status.LIVE),
             roleType == RoleType.CASE,
             roleCategory == RoleCategory.JUDICIAL)
then
    $ra.setStatus(Status.STAGE_1_APPROVED);
    $ra.log("Stage 1 approved : judicial_case_role_mapping_service_create");
    update($ra);
    System.out.println("Rule : judicial_case_role_mapping_service_create");
end;

/*
 * Generic rule for validation of roles deleted by the staff organisational
 * role mapping service.  The mapping service can delete any organisational
 * staff roles.
 */
rule "judicial_case_role_mapping_service_delete"
when
    $rq: Request(
             requestType == RequestType.DELETE)
             //clientId == "ORGANISATIONAL_ROLE_MAPPING_SERVICE")
    $ra: RoleAssignment(
             roleType == RoleType.CASE,
             roleCategory == RoleCategory.JUDICIAL)
then
    //why should we not approved this request here because pattern validation on existing records not making any sense.
    $ra.setStatus(Status.APPROVED);
    $ra.log("Stage 1 approved : judicial_case_role_mapping_service_delete");
    // update was causing for infinite loop
     //update($ra);
    System.out.println("Rule :: judicial_case_role_mapping_service_delete");
end;
