package validationrules.core;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType;
import  uk.gov.hmcts.reform.roleassignment.launchdarkly.FeatureFlagEnum;
import  uk.gov.hmcts.reform.roleassignment.launchdarkly.LDFeatureFlag;

/*
 * mapping for judicial case flow

 */
rule "judicial_case_role_mapping_service_create"
when
    $rq: Request(
                 assignerId == authenticatedUserId)
    $ra: RoleAssignment(status == Status.CREATE_REQUESTED,
                          roleType == RoleType.CASE,
                          roleCategory == RoleCategory.JUDICIAL)
then
    $ra.setStatus(Status.CREATE_APPROVED);
    $ra.log("Create approved : judicial_case_role_mapping_service_create");
    update($ra);
    System.out.println("Rule : judicial_case_role_mapping_service_create");
end;


rule "judicial_case_role_mapping_service_delete"
when
    $rq: Request(assignerId == authenticatedUserId)

    $ra: RoleAssignment(
             status == Status.DELETE_REQUESTED,
             roleType == RoleType.CASE,
             roleCategory == RoleCategory.JUDICIAL)
then
    $ra.setStatus(Status.DELETE_APPROVED);
    $ra.log("Delete approved : judicial_case_role_mapping_service_delete");
     update($ra);
    System.out.println("Rule :: judicial_case_role_mapping_service_delete");
end;

rule "judicial_salaried_judge_case_role_mapping_service_create"
when
     $f : LDFeatureFlag(status && flagName == FeatureFlagEnum.JUDICIALFLAG.getValue())
    $rq: Request(
                 assignerId == authenticatedUserId)
    $ra: RoleAssignment(status == Status.CREATE_REQUESTED,
                          roleType == RoleType.CASE,
                          roleCategory == RoleCategory.JUDICIAL)
then
    $ra.setStatus(Status.CREATE_APPROVED);
    $ra.log("Create approved : judicial_case_role_mapping_service_create");
    update($ra);
    System.out.println("Rule : judicial_case_role_mapping_service_create");
end;


rule "judicial__salaried_judge_case_role_mapping_service_delete"
when
    $f : LDFeatureFlag(status && flagName == FeatureFlagEnum.JUDICIALFLAG.getValue())
    $rq: Request(assignerId == authenticatedUserId)

    $ra: RoleAssignment(
             status == Status.DELETE_REQUESTED,
             roleType == RoleType.CASE,
             roleCategory == RoleCategory.JUDICIAL)
then
    $ra.setStatus(Status.DELETE_APPROVED);
    $ra.log("Delete approved : judicial_case_role_mapping_service_delete");
     update($ra);
    System.out.println("Rule :: judicial_case_role_mapping_service_delete");
end;
