package validationrules.core;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType;


rule "judicial_organisational_role_mapping_service_create"
when
  $rq: Request(byPassOrgDroolRule || clientId == "am_org_role_mapping_service")

   $ra: RoleAssignment(
                status == Status.CREATE_REQUESTED,
                roleType == RoleType.ORGANISATION,
                roleCategory == RoleCategory.JUDICIAL)
then
       $ra.setStatus(Status.CREATE_APPROVED);
       $ra.log("Create approved : judicial_organisational_role_mapping_service_create");
       update($ra);
       System.out.println("Rule : judicial_organisational_role_mapping_service_create");
end;



rule "judicial_organisational_role_mapping_service_delete"
when
    $rq: Request(byPassOrgDroolRule || clientId == "am_org_role_mapping_service")

    $ra: RoleAssignment(
                 status == Status.DELETE_REQUESTED,
                 roleType == RoleType.ORGANISATION,
                 roleCategory == RoleCategory.JUDICIAL)
then
       $ra.setStatus(Status.DELETE_APPROVED);
       $ra.log("Delete approved : judicial_organisational_role_mapping_service_delete");

       update($ra);
       System.out.println("Rule :: judicial_organisational_role_mapping_service_delete");
end;
