package validationrules.core;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;

/*
 * Explicitly reject any role assignments to be created which have not been approved.
 * Salience = -1000 to ensure this is run last, after all rules which could validate
 * the role assignment have had a chance to fire.
 */
rule "reject_unapproved_role_assignments"
salience -1000
when
    $ra: RoleAssignment(status != Status.APPROVED && status != Status.REJECTED)
then
    System.out.println("Rule : reject_unapproved_role_assignments");
    $ra.setStatus(Status.REJECTED);
    $ra.log("Not approved by any rule.");
    update($ra);

end;
