package validationrules.core;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType;

/*
 * Generic rule for validation of roles created by the staff organisational
 * role mapping service.  The mapping service can create any organisational
 * staff roles, and is trusted to get the role attributes right, but note
 * that validation against standard role patterns will still be applied in
 * a later stage of validation.
 */
rule "staff_organisational_role_mapping_service_create"
when
    $rq: Request(
             requestType == RequestType.CREATE)
             //clientId == "ORGANISATIONAL_ROLE_MAPPING_SERVICE")
    $ra: RoleAssignment(
             //Need to check Status Live when replaceExiting=true
             status in(Status.CREATED,Status.LIVE),
             roleType == RoleType.ORGANISATION,
             roleCategory == RoleCategory.STAFF)
then
    $ra.setStatus(Status.STAGE_1_APPROVED);
    $ra.log("Stage 1 approved : staff_organisational_role_mapping_service_create");
    update($ra);
    System.out.println("Rule : staff_organisational_role_mapping_service_create");
end;

// need to create new rule for replace existing =true;

/*
 * Generic rule for validation of roles deleted by the staff organisational
 * role mapping service.  The mapping service can delete any organisational
 * staff roles.
 */
rule "staff_organisational_role_mapping_service_delete"
when
    $rq: Request(
             requestType == RequestType.DELETE)
             //clientId == "ORGANISATIONAL_ROLE_MAPPING_SERVICE")
    $ra: RoleAssignment(
             roleType == RoleType.ORGANISATION,
             roleCategory == RoleCategory.STAFF)
then
    //why should we not approved this request here becuase pattern validation on existing records not making any sense.
    $ra.setStatus(Status.APPROVED);
    $ra.log("Stage 1 approved : staff_organisational_role_mapping_service_delete");
    // update was causing for infinite loop
    //update($ra);
    System.out.println("Rule :: staff_organisational_role_mapping_service_delete");
end;
