package validationrules.iac;
import uk.gov.hmcts.reform.roleassignment.domain.model.Assignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.Request;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.Status;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RequestType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.RoleType
import uk.gov.hmcts.reform.roleassignment.domain.model.ExistingRoleAssignment;
import uk.gov.hmcts.reform.roleassignment.domain.model.CaseAllocatorApproval;
import uk.gov.hmcts.reform.roleassignment.domain.model.Case;
import function uk.gov.hmcts.reform.roleassignment.domain.service.common.ValidationModelService.logMsg;
import uk.gov.hmcts.reform.roleassignment.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.roleassignment.domain.model.enums.FeatureFlagEnum;

import java.time.ZonedDateTime;
import java.time.temporal.ChronoUnit;

/*
 * The below rules are required for Specific and Challenged access
 * It will be toggled on with new IAC_SPECIFIC_1_0 and IAC_CHALLENGED_1_0 DB flag.
 */

/*
 * IAC "challenged-access" case roles self creation user
 */
rule "challenged_access_create_case_role_admin"
when
    $f : FeatureFlag(status && flagName == FeatureFlagEnum.IAC_CHALLENGED_1_0.getValue())
    $rq: Request(
             // The assigner must be the current user.
             assignerId == authenticatedUserId,
             process == "challenged-access",
             reference != null && $referenceId : reference.split("/") && $referenceId.size() > 2
             && $referenceId[0].length() == 16 && $referenceId[1].startsWith("challenged-access"))
    $ra: RoleAssignment(
             actorId == $rq.authenticatedUserId,
             status == Status.CREATE_REQUESTED,
             roleType == RoleType.CASE,
             roleName == "challenged-access-admin",
             roleCategory == RoleCategory.ADMIN,
             grantType == GrantType.CHALLENGED,
             endTime != null && !endTime.isAfter(ZonedDateTime.now().truncatedTo(ChronoUnit.DAYS).plusDays(1)),
             notes != null && notes.size > 0 && notes.toString().length() > 5, /* Make sure there is at least one note with content in it */
             attributes["caseId"] != null && $caseId : attributes["caseId"].asText())
    $c:  Case(
             id == $caseId)
    $e: ExistingRoleAssignment(
             actorId == $ra.actorId,
             roleType == RoleType.ORGANISATION,
             roleCategory == $ra.roleCategory,
             grantType == GrantType.STANDARD,
             classification.isAtLeast($c.securityClassification),
             endTime == null || endTime.isAfter(ZonedDateTime.now()),
             beginTime == null || !beginTime.isAfter(ZonedDateTime.now()),
             attributes["substantive"] != null && attributes["substantive"].asText() == "Y",
             attributes["jurisdiction"] != null && attributes["jurisdiction"].asText() == $c.jurisdiction,
             attributes["caseType"] == null || attributes["caseType"].asText() == $c.caseTypeId,
             attributes["region"] == null || attributes["region"].asText() != $c.region,
             attributes["baseLocation"] == null || attributes["baseLocation"].asText() != $c.baseLocation)
then
    // The classification of $e has already been checked, so access to the case is OK.
    // We set $ra.classification to match the case - if the case is further restricted,
    // then the user will need to request challenged access again, if they still can.
    $ra.setClassification($c.getSecurityClassification());
    // We copy the authorisations to allow the case config to require an authorisation
    // for (particularly judicial) role mappings
    $ra.setAuthorisations($e.getAuthorisations());
    $ra.setAttribute("caseType", $c.getCaseTypeId());
    $ra.setStatus(Status.CREATE_APPROVED);
    $ra.log("Stage 1 approved : challenged_access_create_case_role_admin");
    update($ra);
    logMsg("Rule : challenged_access_create_case_role_admin");
end;
